@startuml user_service
package UserServiceContext <<Rectangle>>{
  object User <<Participant>> #Orange
  object UserServiceContract <<Contract>> #IndianRed

  object UserRegistration <<Propasal>> #IndianRed {
    - userInfo
  }

  object PublishInformationRequest <<FUlfillment>> #IndianRed {
    - createdAt
    - expiredAt
  }

  object PublishInformationConfirmation <<Evidence>> #IndianRed {
    - confirmeType
  }

  object PromoteInformationRequest <<FUlfillment>> #IndianRed {
    - infomation
    - createdAt
    - expiredAt
  }

  object PromoteInformationConfirmation <<Evidence>> #Orange {
    - confirmeType
  }

  object BannedRequest <<FUlfillment>> #IndianRed {
    - createdAt
    - expiredAt
  }

  object BannedConfirmation <<Evidence>> #Orange {
    - createdAt
  }

  object ComplaintBannedRequest <<FUlfillment>> #IndianRed {
    - createdAt
    - expiredAt
  }

  object ComplaintBannedConfirmation <<Evidence>> #Orange {
    - createdAt
  }

  object ActivateRequest <<FUlfillment>> #IndianRed {
    - createdAt
    - expiredAt
  }

  object ActivateConfirmation <<Evidence>> #Orange {
    - createdAt
  }

  object DeleteRequest <<FUlfillment>> #IndianRed {
    - createdAt
    - expiredAt
  }

  object DeleteConfirmation <<Evidence>> #IndianRed {
    - createdAt
  }

  User "1" -left- "1" UserRegistration
  UserRegistration "1" -- "1" UserServiceContract
  UserServiceContract "1" -- "*" PublishInformationRequest
  PublishInformationRequest "1" -- "1" PublishInformationConfirmation
  UserServiceContract "1" -- "*" PromoteInformationRequest
  PromoteInformationRequest "1" -- "1" PromoteInformationConfirmation
  UserServiceContract "1" -- "1" DeleteRequest
  DeleteRequest "1" -- "1" DeleteConfirmation
  UserServiceContract "1" -- "*" BannedRequest
  BannedRequest "1" -- "1" BannedConfirmation
  UserServiceContract "1" -- "1" ActivateRequest
  ActivateRequest "1" -- "1" ActivateConfirmation
  UserServiceContract "1" -- "*" ComplaintBannedRequest
  ComplaintBannedRequest "1" -- "1" ComplaintBannedConfirmation
}

package InformationContext <<Rectangle>> {
  object PromoteRequest <<FUlfillment>> #IndianRed
  object PromoteConfirmation <<Evidence>> #IndianRed

  PromoteConfirmation -- PromoteRequest
}

package OperationContext <<Rectangle>> {
  object UserVerificationRequest <<FUlfillment>> #IndianRed
  object UserVerificationConfirmation <<Evidence>> #IndianRed
  UserVerificationConfirmation --  UserVerificationRequest
}

object IndividualUser <<Party>> #DarkSeaGreen
object PropertyManager <<Party>> #DarkSeaGreen


IndividualUser ..^ User
PropertyManager ..^ User
PromoteInformationConfirmation ^.. PromoteConfirmation
ActivateConfirmation ^.. UserVerificationConfirmation
BannedConfirmation ^.. UserVerificationConfirmation
ComplaintBannedConfirmation ^.. UserVerificationConfirmation
@enduml

@startuml Publish_infomation
package PubulishInformationContext <<Rectangle>> {
  object PublishInfomationContract <<Contract>> #IndianRed
  object Publisher <<Participant>> #Orange
  object whistleblower <<Participant>> #Orange

  object Infomation <<Propasal>> #IndianRed {
    - type
    - location
    - description
    - images
    .. rent only ..
    - propertyInformation
  }

  object NotificationRequest <<FUlfillment>> #IndianRed {
    - type
    - message
    - createdAt
    - expiredAt
  }

  object NotificationConfirmation <<Evidence>> #IndianRed {
    - createdAt
  }

  object HiddenInformationRequest <<FUlfillment>> #IndianRed {
    - type
    - description
    - createdAt
    - expiredAt
  }

  object HiddenInformationConfirmation <<Evidence>> #Orange {
    - createdAt
  }

  object PublishInformationRequest <<FUlfillment>> #IndianRed {
    - createdAt
    - expiredAt
  }

  object PublishInformationConfirmation <<Evidence>> #IndianRed {
    - createdAt
  }

  Publisher "1" -left- "*"  Infomation
  whistleblower "0..1" -- "1"  HiddenInformationRequest
  Infomation "1" -- "1" PublishInfomationContract
  PublishInfomationContract "1" -- "*" HiddenInformationRequest
  HiddenInformationRequest "1" -- "1" HiddenInformationConfirmation
  HiddenInformationRequest -left[hidden]- PublishInformationRequest
  PublishInfomationContract "1" -- "*" PublishInformationRequest
  PublishInformationRequest "1" -- "1" PublishInformationConfirmation
  PublishInfomationContract "1" -- "*" NotificationRequest
  NotificationRequest "1" -- "1" NotificationConfirmation
}
package OperationContext <<Rectangle>> {
  object AuditInformationRequest <<FUlfillment>> #IndianRed
  object AuditInformationConfirmation <<Evidence>> #IndianRed
  AuditInformationConfirmation -- AuditInformationRequest
}

object IndividualAppUser <<Party>> #DarkSeaGreen
object PropertyManagerAppUser <<Party>> #DarkSeaGreen

IndividualAppUser .left.^ Publisher
PropertyManagerAppUser .left.^ Publisher
IndividualAppUser .left.^ whistleblower
PropertyManagerAppUser .left.^ whistleblower
HiddenInformationConfirmation ^.. AuditInformationConfirmation
@enduml

@startuml promote_information
package PromoteInformationContext <<Rectangle>> {
  object PromotionBuyer <<Participant>> #Orange
  object PromoteInformationContract <<Contract>> #IndianRed

  object Promotion <<Propasal>> #IndianRed {
    - infomation
  }

  object DeductRequest <<FUlfillment>> #IndianRed {
    - clickStatistics
    - createdAt
    - expiredAt
  }

  object DeductConfirmation <<Evidence>> #Orange {
    - price
    - createdAt
  }

  object DepositRequest <<FUlfillment>> #IndianRed {
    - amount
    - createdAt
    - expiredAt
  }

  object DepositConfirmation <<Evidence>> #Orange {
    - amount
    - createdAt
  }

  object RefundRequest <<FUlfillment>> #IndianRed {
    - amount
    - createdAt
    - expiredAt
  }

  object RefundConfirmation <<Evidence>> #Orange {
    - amount
    - createdAt
  }

  object PublishPromotionRequest <<FUlfillment>> #IndianRed {
    - createdAt
    - expiredAt
  }

  object PublishPromotionConfirmation <<Evidence>> #IndianRed {
    - createdAt
  }

  object SuspendPromotionRequest <<FUlfillment>> #IndianRed {
    - type
    - createdAt
    - expiredAt
  }

  object SuspendPromotionConfirmation <<Evidence>> #Orange {
    - createdAt
  }

  object InvoiceRequest <<FUlfillment>> #IndianRed {
    - address
    - amount
    - createdAt
    - expiredAt
  }

  object Invoicefirmation <<Evidence>> #Orange {
    - createdAt
  }

  PromoteInformationContract "1" -- "*" DepositRequest
  RefundRequest "1" -- "1" DepositConfirmation
  PromoteInformationContract "1" -- "*" RefundRequest
  DepositRequest "1" -- "1" RefundConfirmation
  PromoteInformationContract "1" -- "*" PublishPromotionRequest
  PublishPromotionRequest "1" -- "1" PublishPromotionConfirmation
  PromoteInformationContract "1" -- "*" SuspendPromotionRequest
  SuspendPromotionRequest "1" -- "1" SuspendPromotionConfirmation
  PromoteInformationContract "1" -- "*" DeductRequest
  DeductRequest "1" -- "1" DeductConfirmation
  PublishPromotionRequest -right[hidden]- SuspendPromotionRequest
  SuspendPromotionRequest -right[hidden]- InvoiceRequest
  PromoteInformationContract "1" -- "*" InvoiceRequest
  InvoiceRequest "1" -- "1" Invoicefirmation
  Promotion -- PromoteInformationContract
  PromotionBuyer -right- Promotion
}

package FinanceContext <<Rectangle>> {
  object PaymentRequest <<FUlfillment>> #IndianRed
  object PaymentConfirmation <<Evidence>> #IndianRed
  object InsufficientSuspendPromotionRequest <<FUlfillment>> #IndianRed
  object InsufficientSuspendPromotionConfirmation <<Evidence>> #IndianRed

  PaymentConfirmation -- PaymentRequest
  InsufficientSuspendPromotionConfirmation -- InsufficientSuspendPromotionRequest
}

package PostContext <<Rectangle>> {
  object PostRequest <<FUlfillment>> #IndianRed
  object PostConfirmation <<Evidence>> #IndianRed

  PostConfirmation -- PostRequest
}

object PropertyManagerAppUser <<Party>> #DarkSeaGreen
object ConsumptionCalculator #Orange
object ADX #Orange

PropertyManagerAppUser ..^ PromotionBuyer
DeductConfirmation ^.. PaymentConfirmation
DepositConfirmation ^.. PaymentConfirmation
RefundConfirmation ^.. PaymentConfirmation
SuspendPromotionConfirmation ^.. InsufficientSuspendPromotionConfirmation
InvoiceRequest -right- ConsumptionCalculator
DeductConfirmation -- ADX
Invoicefirmation ^.. PostConfirmation
@enduml promote_information
